events {
    worker_connections 1024;
}

http {
    set_real_ip_from  172.16.0.0/12;
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;

    log_format json_log escape=json
        '{'
            '"source_ip":"$remote_addr",'
            '"timestamp":"$time_iso8601",'
            '"method":"$request_method",'
            '"path":"$request_uri",'
            '"status":$status,'
            '"response_size":$body_bytes_sent'
        '}';

    server {
        listen 80;
        access_log /var/log/nginx/hng-access.log json_log;

        location / {
            proxy_pass          http://nextcloud:80;
            proxy_set_header    Host              $host;
            proxy_set_header    X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header    X-Real-IP         $remote_addr;
            proxy_read_timeout  300s;
            proxy_connect_timeout 300s;
        }
    }
}
